# Configuration for Kubernetes Cluster and auth service
# This is Kubernetes object - "record of intent" 
apiVersion: apps/v1
kind: Deployment # Deployment object
metadata:
  name: auth
  labels:
    app: auth
spec: # Desired state of the object, k8s tracks the state and updates if needed
  replicas: 2
  selector:
    matchLabels:
      app: auth
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: auth
    spec: # 
      containers:
        - name: auth
          image: woiro/auth
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: auth-configmap
            - secretRef:
                name: auth-secret